### ISSUE TITLE
Toasts

### ISSUE THREAD

**Issue by dododedodonl** [appstract/nova-horizon#2]
When the configured redis connector is not installed, or no connection could be made, toasts keep getting spammed with that message. Would it be possible to limit this behaviour and/or completely disable it?

![ff](https://user-images.githubusercontent.com/100052/101472279-b3172880-3948-11eb-8796-82415a7649a3.png)

On other pages then the horizon dashboard, once every few seconds will be a toast with Connection Refused.

**Comment by vosergey** [comment]
Try to change 
'client' => env('REDIS_CLIENT', 'phpredis')
to 
'client' => env('REDIS_CLIENT', 'predis')
