### ISSUE TITLE
Nova v4 support

### ISSUE THREAD

**Issue by nathan-io** [appstract/nova-horizon#3]
Thank you for this package! Any plans to support Nova v4?

https://nova.laravel.com/docs/4.0/upgrade.html

**Comment by gizburdt** [comment]
Will have a look at it. It's also possible for you to create a PR :)

**Comment by CodeTechNL** [comment]
@gizburdt i've created a pull request. Can you check it out? #4

**Comment by gizburdt** [comment]
@nathan-io @CodeTechNL @metrixinfo You can checkout the master branch (composer: dev-master). If one of you can verify it all works, I will tag 3.0.

Thanks :)

**Comment by metrixinfo** [comment]
I will give it a try today and let you know.  Thanks.

**Comment by metrixinfo** [comment]
@gizburdt 

Tried it locally and pushed it up to my staging servers.  All looking good! 
Thank you very much for getting this out.

**Comment by CodeTechNL** [comment]
@gizburdt any plans for updating the stylesheet? I didn't got time to fix the CSS.

**Comment by gizburdt** [comment]
It's completely fixed :)

**Comment by gizburdt** [comment]
Tagged 3.0.0!

Thanks for the help. If you see some new bugs, please open a new issue :)

**Comment by mstaack** [comment]
really nice! thanks
