### ISSUE TITLE
Can't install on Nova 3 Laravel 8

### ISSUE THREAD

**Issue by jonathanlaf** [appstract/nova-horizon#8]
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
*[2022-07-28 15:40:10] local.ERROR: Method router does not exist. {"exception":"[object] (BadMethodCallException(code: 0): Method router does not exist. at /var/www/html/vendor/laravel/nova/src/Nova.php:1002)
[stacktrace]
#0 /var/www/html/vendor/appstract/nova-horizon/src/NovaHorizonServiceProvider.php(49): Laravel\\Nova\\Nova::__callStatic()
#1 /var/www/html/vendor/appstract/nova-horizon/src/NovaHorizonServiceProvider.php(23): Appstract\\NovaHorizon\\NovaHorizonServiceProvider->routes()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(967): Appstract\\NovaHorizon\\NovaHorizonServiceProvider->Appstract\\NovaHorizon\\{closure}()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(910): Illuminate\\Foundation\\Application->fireAppCallbacks()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\\Foundation\\Application->boot()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(237): Illuminate\\Foundation\\Bootstrap\\BootProviders->bootstrap()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(310): Illuminate\\Foundation\\Application->bootstrapWith()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(127): Illuminate\\Foundation\\Console\\Kernel->bootstrap()
#8 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#9 {main}
"} 

   BadMethodCallException 

  Method router does not exist.

**Comment by gizburdt** [comment]
Version ^3.0 is for Nova 4, for Nova 3 you need to install version ^2.0
